; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]

platform = ststm32
board = lora_e5_dev_board
framework = arduino
lib_deps =
    adafruit/Adafruit BME280 Library@^2.3.0
    claws/BH1750@^1.3.0
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-140
upload_protocol = custom
upload_port = /dev/cu.usbmodem1202
upload_flags =
    -f
    ./stm32_flash.cfg
upload_command = openocd $UPLOAD_FLAGS -c "program $SOURCE 0x08000000 verify reset exit"
debug_tool = custom
debug_server =
    openocd
    -f
    ./stm32_flash.cfg
debug_init_break = tbreak main

[env:t_sensor]
build_src_filter = +<tests/sensor.cpp>
